[workspace]
resolver = "3"
members = [
    "Crates/fusion-pcu",
    "Crates/macros",
    "Crates/backends/rocm",
    "Crates/backends/spirv",
    "Crates/runner",
    "Crates/dialects/tensor",
    "Crates/dialects/vm-reference",
    "Examples/rocm",
    "Examples/vulkan",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Private Asylum LLC"]
license = "Apache-2.0"
repository = "https://github.com/Private-Asylum/Fusion-PCU"

[workspace.dependencies]
fusion-pcu = { path = "Crates/fusion-pcu", default-features = false }
fusion-pcu-macros = { path = "Crates/macros" }
fusion-pcu-rocm = { path = "Crates/backends/rocm", default-features = false }
fusion-pcu-spirv = { path = "Crates/backends/spirv", default-features = false }
fusion-pcu-runner = { path = "Crates/runner", default-features = false }

ash = { version = "0.38.0", default-features = false, features = ["loaded"] }
proc-macro2 = "1.0.103"
quote = "1.0.41"
syn = { version = "2.0.108", features = ["full"] }
winit = "0.30"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_arch, values("spirv"))'] }

[profile.bench]
debug = 2
