[package]
name = "fusion-pcu"
description = "Backend-neutral intermediate representation and execution contracts for coprocessors"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["rlib"]
path = "fusion-pcu.rs"

[features]
default = []
std = []
hosted = ["std"]

[lints]
workspace = true
