[package]
name = "fusion-pcu-example-vulkan"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[[bin]]
name = "fusion-vulkan-example"
path = "main.rs"

[features]
default = ["std", "hosted"]
hosted = ["fusion-pcu/hosted"]
std = ["fusion-pcu/std"]

[dependencies]
fusion-pcu.workspace = true
fusion-pcu-vulkan = { workspace = true, features = ["hosted"] }
fusion-pcu-macros.workspace = true
winit.workspace = true

[dev-dependencies]
fusion-pcu-spirv.workspace = true

[lints]
workspace = true
